/**
 * @dino/cli — dino init (interactive onboarding)
 * Issue #322. Generates .dino.yml through conversational Q&A.
 *
 * INV-1: Never writes secrets into .dino.yml.
 * INV-2: Checks for existing config before overwriting.
 * INV-3: Generated YAML passes dino validate (same Zod schema as loadCliConfig).
 * INV-4: No tenant, no auth — runs pre-config.
 * INV-5: Endpoint validation timeout 5s.
 */

import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import prompts from 'prompts';

export interface InitFlags {
  quiet?: boolean;
  /** Skip existing config overwrite check */
  force?: boolean;
}

/** Build YAML string from answers. INV-1: no secrets. */
export function buildConfigYaml(answers: {
  endpoint: string;
  protocol: string;
  format: string;
  authEnabled: boolean;
  reasoningEnabled: boolean;
}): string {
  const lines: string[] = [
    '# yaml-language-server: $schema=https://usedino.dev/schema.json', // comment: IDE schema URL
    '# Generated by dino init — see docs/CONFIGURATION.md for all options',
    '',
    `endpoint: ${answers.endpoint}`,
    `protocol: ${answers.protocol}`,
    `format: ${answers.format}`,
  ];

  if (answers.authEnabled) {
    lines.push('auth:', '  enabled: true');
  }

  if (answers.reasoningEnabled) {
    lines.push(
      '',
      '# AI reasoning enabled — set ANTHROPIC_API_KEY env var before running dino scan',
    );
  }

  lines.push('');
  return lines.join('\n');
}

/** Prompt objects for dino init (extracted to keep runInit cognitive complexity low). */
function initPromptQuestions(): Parameters<typeof prompts>[0] {
  return [
    {
      type: 'text',
      name: 'endpoint',
      message: "What's your API endpoint URL?",
      validate: (v: string) => {
        try {
          new URL(v);
          return true;
        } catch {
          return 'Please enter a valid URL (e.g., https://api.example.com/graphql)';
        }
      },
    },
    {
      type: 'select',
      name: 'protocol',
      message: 'What protocol does your API use?',
      choices: [{ title: 'GraphQL', value: 'graphql' }],
      initial: 0,
    },
    {
      type: 'confirm',
      name: 'authEnabled',
      message: 'Does your API require authentication?',
      initial: false,
    },
    {
      type: (prev: boolean) => (prev ? 'text' : null),
      name: 'authEnvVar',
      message: 'Environment variable name for your token?',
      initial: 'DINO_API_TOKEN',
    },
    {
      type: 'select',
      name: 'format',
      message: 'Output format?',
      choices: [
        { title: 'JSON (machine-readable)', value: 'json' },
        { title: 'Markdown (human-readable)', value: 'markdown' },
      ],
      initial: 0,
    },
    {
      type: 'confirm',
      name: 'reasoningEnabled',
      message: 'Enable AI-powered analysis? (Requires Anthropic API key)',
      initial: false,
    },
    {
      type: (prev: boolean) => (prev ? 'text' : null),
      name: 'aiKeyVar',
      message: 'Environment variable for Anthropic key?',
      initial: 'ANTHROPIC_API_KEY',
    },
  ];
}

function printInitNextSteps(answers: {
  authEnabled: boolean;
  reasoningEnabled: boolean;
  authEnvVar?: string;
  aiKeyVar?: string;
}): void {
  console.info('Next steps:');
  if (
    answers.authEnabled &&
    typeof answers.authEnvVar === 'string' &&
    answers.authEnvVar.length > 0
  ) {
    console.info(`  export ${answers.authEnvVar}="your-token-here"`);
  }
  if (
    answers.reasoningEnabled &&
    typeof answers.aiKeyVar === 'string' &&
    answers.aiKeyVar.length > 0
  ) {
    console.info(`  export ${answers.aiKeyVar}="sk-ant-..."`);
  }
  console.info('  dino scan\n');
}

/** Validate endpoint reachability (INV-5: 5s timeout). Returns true if reachable. */
export async function checkEndpoint(url: string): Promise<boolean> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000); // determinism:allowed
  try {
    await fetch(url, { method: 'HEAD', signal: controller.signal });
    return true;
  } catch {
    return false;
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * dino init [--force]
 *
 * Interactive onboarding — generates .dino.yml.
 * INV-4: No tenant required. Runs before any config exists.
 */
export async function runInit(flags: InitFlags): Promise<number> {
  const configPath = resolve(process.cwd(), '.dino.yml');

  if (!flags.force && existsSync(configPath)) {
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: '.dino.yml already exists. Overwrite?',
      initial: false,
    });
    if (overwrite !== true) {
      console.info('Aborted. Existing config preserved.');
      return 0;
    }
  }

  if (!flags.quiet) {
    console.info('\nWelcome to Dino — API Intelligence\n');
    console.info("Let's set up your project.\n");
  }

  const answers = await prompts(initPromptQuestions(), {
    onCancel: () => {
      console.info('\nAborted. No config written.');
    },
  });

  // Cancel or incomplete flow: format is always 'json' | 'markdown' when finished (select value).
  if (typeof answers.format !== 'string') {
    return 0;
  }

  const endpoint = answers.endpoint as string;
  const protocol = answers.protocol as string;
  const format = answers.format;
  const authEnabled = answers.authEnabled === true;
  const reasoningEnabled = answers.reasoningEnabled === true;

  if (!flags.quiet) {
    const reachable = await checkEndpoint(endpoint);
    if (!reachable) {
      console.warn(`[warn] Could not reach ${endpoint} — continuing anyway.`);
    }
  }

  const yaml = buildConfigYaml({
    endpoint,
    protocol,
    format,
    authEnabled,
    reasoningEnabled,
  });

  if (!flags.quiet) {
    console.info('\n--- .dino.yml ---');
    console.info(yaml);
    console.info('-----------------\n');
  }

  try {
    writeFileSync(configPath, yaml, 'utf-8');
  } catch (err) {
    console.error(`Failed to write .dino.yml: ${err instanceof Error ? err.message : String(err)}`);
    return 1;
  }

  console.info('Created .dino.yml\n');

  printInitNextSteps({
    authEnabled,
    reasoningEnabled,
    authEnvVar: answers.authEnvVar as string | undefined,
    aiKeyVar: answers.aiKeyVar as string | undefined,
  });

  return 0;
}
