/**
 * @dino/cli — dino init (interactive onboarding)
 * Issue #322. Generates .dino.yml through conversational Q&A.
 *
 * INV-1: Never writes secrets into .dino.yml.
 * INV-2: Checks for existing config before overwriting.
 * INV-3: Generated YAML passes dino validate (same Zod schema as loadCliConfig).
 * INV-4: No tenant, no auth — runs pre-config.
 * INV-5: Endpoint validation timeout 5s.
 */

import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import prompts from 'prompts';
import { detectUi, colorize } from '../shared/ui';
import type { UiOptions } from '../shared/ui';
import { shouldRenderInkView } from '../ink/render';
import { CLI_VERSION } from '../version';

export interface InitFlags {
  quiet?: boolean;
  /** Skip existing config overwrite check */
  force?: boolean;
}

/** Build YAML string from answers. INV-1: no secrets. */
export function buildConfigYaml(answers: {
  endpoint: string;
  protocol: string;
  format: string;
  authEnabled: boolean;
  reasoningEnabled: boolean;
}): string {
  const lines: string[] = [
    '# yaml-language-server: $schema=https://usedino.dev/schema.json', // comment: IDE schema URL
    '# Generated by dino init — see docs/CONFIGURATION.md for all options',
    '',
    `endpoint: ${answers.endpoint}`,
    `protocol: ${answers.protocol}`,
    `format: ${answers.format}`,
  ];

  if (answers.authEnabled) {
    lines.push('auth:', '  enabled: true');
  }

  if (answers.reasoningEnabled) {
    lines.push(
      '',
      '# AI reasoning enabled — set ANTHROPIC_API_KEY env var before running dino scan',
    );
  }

  lines.push('');
  return lines.join('\n');
}

/** Case-insensitive check: URL path ends with /graphql (trailing slash + querystring tolerant). INV-UX-6. */
export function urlPathEndsWithGraphQL(url: string): boolean {
  try {
    const parsed = new URL(url);
    // Strip ALL trailing slashes (greedy), then compare lowercase. Greedy
    // handles copy-paste artifacts like '/graphql//' that are functionally
    // identical to '/graphql' (Maciver LOW urlMultiTrailingSlashEdge).
    const path = parsed.pathname.replace(/\/+$/, '').toLowerCase();
    return path.endsWith('/graphql');
  } catch {
    // Invalid URL — the endpoint prompt's validate() already rejects these before this helper runs.
    return false;
  }
}

/**
 * Prompt for endpoint with a soft /graphql-suffix warning (#1023).
 * Loops the endpoint prompt if the user declines the warning. INV-UX-4, INV-UX-5.
 *
 * @returns the confirmed endpoint, or null on cancellation.
 */
export async function promptEndpointWithGraphQLWarning(): Promise<string | null> {
  while (true) {
    const { endpoint } = await prompts({
      type: 'text',
      name: 'endpoint',
      message: "What's your API endpoint URL?",
      validate: (v: string) => {
        try {
          new URL(v);
          return true;
        } catch {
          return 'Please enter a valid URL (e.g., https://api.example.com/graphql)';
        }
      },
    });
    if (typeof endpoint !== 'string') return null;

    if (urlPathEndsWithGraphQL(endpoint)) return endpoint;

    const { confirm } = await prompts({
      type: 'confirm',
      name: 'confirm',
      message:
        'URL does not end with /graphql — GraphQL endpoints typically expose introspection at a /graphql path. Continue with this URL anyway?',
      initial: false,
    });
    if (confirm === true) return endpoint;
    if (typeof confirm !== 'boolean') return null;
    // else: user answered 'no' — loop to re-prompt the endpoint
  }
}

/** Prompt objects AFTER endpoint — protocol, auth, format, reasoning. */
function remainingInitPromptQuestions(): Parameters<typeof prompts>[0] {
  return [
    {
      type: 'select',
      name: 'protocol',
      message: 'What protocol does your API use?',
      choices: [{ title: 'GraphQL', value: 'graphql' }],
      initial: 0,
    },
    {
      type: 'confirm',
      name: 'authEnabled',
      message: 'Does your API require authentication?',
      initial: false,
    },
    {
      type: (prev: boolean) => (prev ? 'text' : null),
      name: 'authEnvVar',
      message: 'Environment variable name for your token?',
      initial: 'DINO_API_TOKEN',
    },
    {
      type: 'select',
      name: 'format',
      message: 'Output format?',
      choices: [
        { title: 'JSON (machine-readable)', value: 'json' },
        { title: 'Markdown (human-readable)', value: 'markdown' },
      ],
      initial: 0,
    },
    {
      type: 'confirm',
      name: 'reasoningEnabled',
      message: 'Enable AI-powered analysis? (Requires Anthropic API key)',
      initial: false,
    },
    {
      type: (prev: boolean) => (prev ? 'text' : null),
      name: 'aiKeyVar',
      message: 'Environment variable for Anthropic key?',
      initial: 'ANTHROPIC_API_KEY',
    },
  ];
}

/** Lines after the "Next steps:" heading (export hints + dino scan). */
function buildInitNextStepLines(answers: {
  authEnabled: boolean;
  reasoningEnabled: boolean;
  authEnvVar?: string;
  aiKeyVar?: string;
}): string[] {
  const lines: string[] = [];
  if (
    answers.authEnabled &&
    typeof answers.authEnvVar === 'string' &&
    answers.authEnvVar.length > 0
  ) {
    lines.push(`  export ${answers.authEnvVar}="your-token-here"`);
  }
  if (
    answers.reasoningEnabled &&
    typeof answers.aiKeyVar === 'string' &&
    answers.aiKeyVar.length > 0
  ) {
    lines.push(`  export ${answers.aiKeyVar}="sk-ant-..."`);
  }
  lines.push('  dino scan');
  return lines;
}

function printInitNextSteps(
  answers: {
    authEnabled: boolean;
    reasoningEnabled: boolean;
    authEnvVar?: string;
    aiKeyVar?: string;
  },
  ui: UiOptions,
): void {
  console.info(colorize('Next steps:', 'bold', ui));
  for (const line of buildInitNextStepLines(answers)) {
    console.info(line);
  }
  console.info('');
}

async function tryRenderInitInkSummary(params: {
  ui: UiOptions;
  quiet: boolean | undefined;
  configPath: string;
  endpoint: string;
  protocol: string;
  format: string;
  nextStepAnswers: {
    authEnabled: boolean;
    reasoningEnabled: boolean;
    authEnvVar?: string;
    aiKeyVar?: string;
  };
}): Promise<boolean> {
  if (!shouldRenderInkView(params.ui, { quiet: params.quiet })) {
    return false;
  }
  try {
    const React = await import('react');
    const { renderViewSafe } = await import('../ink/render');
    const { InitView } = await import('../views/InitView');
    const lines: string[] = [
      `Config: ${params.configPath}`,
      `Endpoint: ${params.endpoint}`,
      `Protocol: ${params.protocol}`,
      `Format: ${params.format}`,
      'Next steps:',
      ...buildInitNextStepLines(params.nextStepAnswers),
    ];
    return renderViewSafe(
      React.createElement(InitView, {
        version: CLI_VERSION,
        lines,
        colored: params.ui.colored,
      }),
    );
  } catch (error_) {
    console.warn(
      '[dino] Ink init view failed:',
      error_ instanceof Error ? error_.message : String(error_),
    );
    return false;
  }
}

/** Validate endpoint reachability (INV-5: 5s timeout). Returns true if reachable. */
export async function checkEndpoint(url: string): Promise<boolean> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000); // determinism:allowed
  try {
    await fetch(url, { method: 'HEAD', signal: controller.signal });
    return true;
  } catch {
    return false;
  } finally {
    clearTimeout(timeout);
  }
}

async function promptOverwriteWhenConfigExists(
  configPath: string,
  flags: InitFlags,
): Promise<'aborted' | 'proceed'> {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- path is always cwd/.dino.yml
  if (flags.force || !existsSync(configPath)) return 'proceed';
  const { overwrite } = await prompts({
    type: 'confirm',
    name: 'overwrite',
    message: '.dino.yml already exists. Overwrite?',
    initial: false,
  });
  if (overwrite !== true) {
    console.info('Aborted. Existing config preserved.');
    return 'aborted';
  }
  return 'proceed';
}

function printInitWelcomeIfNotQuiet(flags: InitFlags, ui: UiOptions): void {
  if (flags.quiet) return;
  console.info(colorize('\nWelcome to Dino — API Intelligence\n', 'bold', ui));
  console.info("Let's set up your project.\n");
}

async function maybeWarnUnreachableInitEndpoint(endpoint: string, quiet: boolean): Promise<void> {
  if (quiet) return;
  const reachable = await checkEndpoint(endpoint);
  if (!reachable) {
    console.warn(`[warn] Could not reach ${endpoint} — continuing anyway.`);
  }
}

function printYamlPreviewIfNotQuiet(yaml: string, quiet: boolean): void {
  if (quiet) return;
  console.info('\n--- .dino.yml ---');
  console.info(yaml);
  console.info('-----------------\n');
}

function writeInitConfigOrReturnError(configPath: string, yaml: string): number {
  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- path is always cwd/.dino.yml
    writeFileSync(configPath, yaml, 'utf-8');
    return 0;
  } catch (err) {
    console.error(`Failed to write .dino.yml: ${err instanceof Error ? err.message : String(err)}`);
    return 1;
  }
}

/**
 * dino init [--force]
 *
 * Interactive onboarding — generates .dino.yml.
 * INV-4: No tenant required. Runs before any config exists.
 */
export async function runInit(flags: InitFlags): Promise<number> {
  const configPath = resolve(process.cwd(), '.dino.yml');
  const ui = detectUi({ quiet: flags.quiet });

  const overwriteOutcome = await promptOverwriteWhenConfigExists(configPath, flags);
  if (overwriteOutcome === 'aborted') return 0;

  printInitWelcomeIfNotQuiet(flags, ui);

  const endpoint = await promptEndpointWithGraphQLWarning();
  if (endpoint === null) {
    console.info('\nAborted. No config written.');
    return 0;
  }

  const answers = await prompts(remainingInitPromptQuestions(), {
    onCancel: () => {
      console.info('\nAborted. No config written.');
    },
  });

  // Cancel or incomplete flow: format is always 'json' | 'markdown' when finished (select value).
  if (typeof answers.format !== 'string') {
    return 0;
  }

  const protocol = answers.protocol as string;
  const format = answers.format;
  const authEnabled = answers.authEnabled === true;
  const reasoningEnabled = answers.reasoningEnabled === true;

  await maybeWarnUnreachableInitEndpoint(endpoint, flags.quiet === true);

  const yaml = buildConfigYaml({
    endpoint,
    protocol,
    format,
    authEnabled,
    reasoningEnabled,
  });

  printYamlPreviewIfNotQuiet(yaml, flags.quiet === true);

  const writeCode = writeInitConfigOrReturnError(configPath, yaml);
  if (writeCode !== 0) return writeCode;

  console.info(colorize('✔ Created .dino.yml\n', 'green', ui));

  const nextStepAnswers = {
    authEnabled,
    reasoningEnabled,
    authEnvVar: answers.authEnvVar as string | undefined,
    aiKeyVar: answers.aiKeyVar as string | undefined,
  };

  const inkSummary = await tryRenderInitInkSummary({
    ui,
    quiet: flags.quiet,
    configPath,
    endpoint,
    protocol,
    format,
    nextStepAnswers,
  });

  if (!inkSummary) {
    printInitNextSteps(nextStepAnswers, ui);
  }

  return 0;
}
