/**
 * @dino/cli — dino init (interactive onboarding)
 * Issue #322 / #2160. Generates .dino.yml through conversational Q&A.
 *
 * INV-1: Never writes secrets into .dino.yml.
 * INV-2: Checks for existing config before overwriting.
 * INV-3: Generated YAML passes dino validate (same Zod schema as loadCliConfig).
 * INV-4: No tenant, no auth — runs pre-config.
 * INV-5: Endpoint validation timeout 5s.
 */

import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import prompts from 'prompts';
import { shouldRenderInkView } from '../ink/InkRender';
import { headerAuthPromptQuestions } from '../shared/init-header-auth';
import {
  appendOAuth2YamlLines,
  buildOAuth2AuthAnswers,
  oauth2AuthPromptQuestions,
  oauth2NextStepLines,
  type InitOAuth2Answers,
} from '../shared/init-oauth2';
import { detectUi, colorize, printNotice } from '../shared/ui';
import { CLI_VERSION } from '../version';
import type { UiOptions } from '../shared/ui';

export interface InitFlags {
  quiet?: boolean;
  /** Skip existing config overwrite check */
  force?: boolean;
  /** #2160: when user opts into "Run a scan now?", invoke this (wired by index). */
  onScanNow?: (() => Promise<number>) | undefined;
}

/** #2160/#2161: auth answers for generated .dino.yml (never a secret value). */
export type InitAuthAnswers =
  | { type: 'none' }
  | { type: 'header'; header: string; scheme?: string; valueEnv: string }
  | InitOAuth2Answers;

/** Build YAML string from answers. INV-1: no secrets. */
export function buildConfigYaml(answers: {
  endpoint: string;
  protocol: string;
  auth?: InitAuthAnswers;
  specUrl?: string;
}): string {
  const lines: string[] = [
    // Branded canonical schema (mirrors packages/cli/schema.json); resolves for IDE validation.
    '# yaml-language-server: $schema=https://usedino.dev/schema.json',
    '# Generated by dino init: see https://docs.usedino.dev for all options',
    '',
    `endpoint: ${answers.endpoint}`,
    `protocol: ${answers.protocol}`,
  ];

  if (
    answers.protocol === 'rest' &&
    typeof answers.specUrl === 'string' &&
    answers.specUrl.length > 0
  ) {
    lines.push(`specUrl: ${answers.specUrl}`);
  }

  // #2160/#2161: default format is markdown (flag-level); do not emit format in generated yaml.
  // Emit a real auth block (header or oauth2); never `enabled: true`.
  const auth = answers.auth;
  if (auth?.type === 'header') {
    lines.push('auth:', '  type: header', `  header: ${auth.header}`);
    if (auth.scheme && auth.scheme.length > 0) {
      lines.push(`  scheme: ${auth.scheme}`);
    }
    lines.push(`  valueEnv: ${auth.valueEnv}`);
  } else if (auth?.type === 'oauth2') {
    appendOAuth2YamlLines(lines, auth);
  }

  lines.push('');
  return lines.join('\n');
}

/** Case-insensitive check: URL path ends with /graphql (trailing slash + querystring tolerant). INV-UX-6. */
export function urlPathEndsWithGraphQL(url: string): boolean {
  try {
    const parsed = new URL(url);
    // Strip ALL trailing slashes (greedy), then compare lowercase. Greedy
    // handles copy-paste artifacts like '/graphql//' that are functionally
    // identical to '/graphql' (Maciver LOW urlMultiTrailingSlashEdge).
    let path = parsed.pathname;
    while (path.endsWith('/')) path = path.slice(0, -1);
    path = path.toLowerCase();
    return path.endsWith('/graphql');
  } catch {
    // Invalid URL — the endpoint prompt's validate() already rejects these before this helper runs.
    return false;
  }
}

/**
 * Prompt for endpoint with a soft /graphql-suffix warning (#1023).
 * Loops the endpoint prompt if the user declines the warning. INV-UX-4, INV-UX-5.
 *
 * @returns the confirmed endpoint, or null on cancellation.
 */
export async function promptEndpointWithGraphQLWarning(): Promise<string | null> {
  while (true) {
    const { endpoint } = await prompts({
      type: 'text',
      name: 'endpoint',
      message: "What's your API endpoint URL?",
      validate: (v: string) => {
        try {
          new URL(v);
          return true;
        } catch {
          return 'Please enter a valid URL (e.g., https://api.example.com/graphql)';
        }
      },
      stdout: process.stderr,
    });
    if (typeof endpoint !== 'string') return null;

    if (urlPathEndsWithGraphQL(endpoint)) return endpoint;

    const { confirm } = await prompts({
      type: 'confirm',
      name: 'confirm',
      message:
        'URL does not end with /graphql: GraphQL endpoints typically expose introspection at a /graphql path. Continue with this URL anyway?',
      initial: false,
      stdout: process.stderr,
    });
    if (confirm === true) return endpoint;
    if (typeof confirm !== 'boolean') return null;
    // else: user answered 'no' — loop to re-prompt the endpoint
  }
}

/** Interactive prompt chrome goes to stderr (INV-4 / #206 Change F). */
const INIT_PROMPT_STDERR = { stdout: process.stderr } as const;

const INIT_PROTOCOL_CHOICES = [
  { title: 'GraphQL', value: 'graphql' },
  { title: 'REST (OpenAPI)', value: 'rest' },
];

const INIT_AUTH_CHOICES = [
  { title: 'None', value: 'none' },
  { title: 'Header token (Bearer / API key)', value: 'header' },
  { title: 'OAuth2 (client credentials)', value: 'oauth2' },
];

export interface RemainingInitPromptOptions {
  /** #2160: skip protocol + specUrl when endpoint path ends with /graphql. */
  skipProtocol?: boolean;
}

/** Prompt objects AFTER endpoint: optional protocol/specUrl + auth sub-flow (#2160). */
export function remainingInitPromptQuestions(
  opts?: RemainingInitPromptOptions,
): Parameters<typeof prompts>[0] {
  const skipProtocol = opts?.skipProtocol === true;
  const questions: Parameters<typeof prompts>[0] = [];

  if (!skipProtocol) {
    questions.push(
      {
        type: 'select',
        name: 'protocol',
        message: 'What protocol does your API use?',
        choices: INIT_PROTOCOL_CHOICES,
        initial: 0,
        ...INIT_PROMPT_STDERR,
      },
      {
        type: (prev: string) => (prev === 'rest' ? 'text' : null),
        name: 'specUrl',
        message: 'OpenAPI spec URL or file path',
        validate: (v: string) =>
          v.trim().length > 0 ? true : 'Please enter a spec URL or file path',
        ...INIT_PROMPT_STDERR,
      },
    );
  }

  questions.push(
    {
      type: 'select',
      name: 'authType',
      message: 'How does your API authenticate?',
      choices: INIT_AUTH_CHOICES,
      initial: 0,
      ...INIT_PROMPT_STDERR,
    },
    ...headerAuthPromptQuestions(),
    ...oauth2AuthPromptQuestions(),
  );

  return questions;
}

function buildAuthAnswers(answers: {
  authType?: unknown;
  authHeader?: unknown;
  authScheme?: unknown;
  authValueEnv?: unknown;
  oauth2TokenEndpoint?: unknown;
  oauth2ClientIdEnv?: unknown;
  oauth2ClientSecretEnv?: unknown;
  oauth2Scope?: unknown;
}): InitAuthAnswers | undefined {
  if (answers.authType === 'oauth2') {
    return buildOAuth2AuthAnswers(answers);
  }
  if (answers.authType !== 'header') return { type: 'none' };
  const header =
    typeof answers.authHeader === 'string' && answers.authHeader.trim().length > 0
      ? answers.authHeader.trim()
      : 'Authorization';
  const valueEnv =
    typeof answers.authValueEnv === 'string' && answers.authValueEnv.trim().length > 0
      ? answers.authValueEnv.trim()
      : 'DINO_API_TOKEN';
  const schemeRaw = typeof answers.authScheme === 'string' ? answers.authScheme.trim() : '';
  if (schemeRaw.length > 0) {
    return { type: 'header', header, scheme: schemeRaw, valueEnv };
  }
  return { type: 'header', header, valueEnv };
}

/** Lines after the "Next steps:" heading (export hints + dino scan). */
function buildInitNextStepLines(answers: { auth?: InitAuthAnswers | undefined }): string[] {
  const lines: string[] = [];
  const auth = answers.auth;
  if (auth?.type === 'header') {
    lines.push(`  export ${auth.valueEnv}="your-token-here"`);
  } else if (auth?.type === 'oauth2') {
    lines.push(...oauth2NextStepLines(auth));
  }
  lines.push('  dino scan');
  return lines;
}

function printInitNextSteps(answers: { auth?: InitAuthAnswers | undefined }, ui: UiOptions): void {
  // #175: next-steps are chrome → stderr
  printNotice('Next steps:', ui);
  for (const line of buildInitNextStepLines(answers)) {
    printNotice(line, ui);
  }
}

async function tryRenderInitInkSummary(params: {
  ui: UiOptions;
  quiet: boolean | undefined;
  configPath: string;
  endpoint: string;
  protocol: string;
  nextStepAnswers: {
    auth?: InitAuthAnswers | undefined;
  };
}): Promise<boolean> {
  if (!shouldRenderInkView(params.ui, { quiet: params.quiet })) {
    return false;
  }
  try {
    const React = await import('react');
    const { renderViewSafe } = await import('../ink/InkRender');
    const { InitView } = await import('../views/InitView');
    const lines: string[] = [
      `Config: ${params.configPath}`,
      `Endpoint: ${params.endpoint}`,
      `Protocol: ${params.protocol}`,
      'Next steps:',
      ...buildInitNextStepLines(params.nextStepAnswers),
    ];
    return renderViewSafe(
      React.createElement(InitView, {
        version: CLI_VERSION,
        lines,
        colored: params.ui.colored,
      }),
    );
  } catch (error_) {
    console.warn(
      '[dino] Ink init view failed:',
      error_ instanceof Error ? error_.message : String(error_),
    );
    return false;
  }
}

/** Validate endpoint reachability (INV-5: 5s timeout). Returns true if reachable. */
export async function checkEndpoint(url: string): Promise<boolean> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 5000); // determinism:allowed
  try {
    await fetch(url, { method: 'HEAD', signal: controller.signal }); // determinism:allowed
    return true;
  } catch {
    return false;
  } finally {
    clearTimeout(timeout);
  }
}

async function promptOverwriteWhenConfigExists(
  configPath: string,
  flags: InitFlags,
): Promise<'aborted' | 'proceed'> {
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- path is always cwd/.dino.yml
  if (flags.force || !existsSync(configPath)) return 'proceed';
  const { overwrite } = await prompts({
    type: 'confirm',
    name: 'overwrite',
    message: '.dino.yml already exists. Overwrite?',
    initial: false,
    stdout: process.stderr,
  });
  if (overwrite !== true) {
    console.info('Aborted. Existing config preserved.');
    return 'aborted';
  }
  return 'proceed';
}

function printInitWelcomeIfNotQuiet(flags: InitFlags, ui: UiOptions): void {
  if (flags.quiet) return;
  // #175: welcome banner is chrome → stderr
  printNotice('Welcome to Dino - API Intelligence', ui);
  printNotice("Let's set up your project.", ui);
}

async function maybeWarnUnreachableInitEndpoint(endpoint: string, quiet: boolean): Promise<void> {
  if (quiet) return;
  const reachable = await checkEndpoint(endpoint);
  if (!reachable) {
    console.warn(`[warn] Could not reach ${endpoint}: continuing anyway.`);
  }
}

function printYamlPreviewIfNotQuiet(yaml: string, quiet: boolean): void {
  if (quiet) return;
  // #175: YAML preview is interactive chrome → stderr (keep YAML readable, no notice prefix)
  console.error('\n--- .dino.yml ---');
  console.error(yaml);
  console.error('-----------------\n');
}

function writeInitConfigOrReturnError(configPath: string, yaml: string): number {
  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- path is always cwd/.dino.yml
    writeFileSync(configPath, yaml, 'utf-8');
    return 0;
  } catch (err) {
    console.error(`Failed to write .dino.yml: ${err instanceof Error ? err.message : String(err)}`);
    return 1;
  }
}

/**
 * dino init [--force]
 *
 * Interactive onboarding — generates .dino.yml.
 * INV-4: No tenant required. Runs before any config exists.
 */
export async function runInit(flags: InitFlags): Promise<number> {
  const configPath = resolve(process.cwd(), '.dino.yml');
  const ui = detectUi({ quiet: flags.quiet });

  const overwriteOutcome = await promptOverwriteWhenConfigExists(configPath, flags);
  if (overwriteOutcome === 'aborted') return 0;

  printInitWelcomeIfNotQuiet(flags, ui);

  const endpoint = await promptEndpointWithGraphQLWarning();
  if (endpoint === null) {
    console.info('\nAborted. No config written.');
    return 0;
  }

  const skipProtocol = urlPathEndsWithGraphQL(endpoint);
  const answers = await prompts(remainingInitPromptQuestions({ skipProtocol }), {
    onCancel: () => {
      console.info('\nAborted. No config written.');
    },
  });

  // Cancel or incomplete flow: authType is always set when finished.
  if (typeof answers.authType !== 'string') {
    return 0;
  }
  if (!skipProtocol && typeof answers.protocol !== 'string') {
    return 0;
  }

  const protocol = skipProtocol ? 'graphql' : (answers.protocol as string);
  const auth = buildAuthAnswers(answers);

  await maybeWarnUnreachableInitEndpoint(endpoint, flags.quiet === true);

  const yaml = buildConfigYaml({
    endpoint,
    protocol,
    ...(auth ? { auth } : {}),
    ...(typeof answers.specUrl === 'string' ? { specUrl: answers.specUrl } : {}),
  });

  printYamlPreviewIfNotQuiet(yaml, flags.quiet === true);

  const writeCode = writeInitConfigOrReturnError(configPath, yaml);
  if (writeCode !== 0) return writeCode;

  console.info(colorize('✔ Created .dino.yml\n', 'green', ui));

  const nextStepAnswers = { auth };

  const inkSummary = await tryRenderInitInkSummary({
    ui,
    quiet: flags.quiet,
    configPath,
    endpoint,
    protocol,
    nextStepAnswers,
  });

  if (!inkSummary) {
    printInitNextSteps(nextStepAnswers, ui);
  }

  // #2160: offer an immediate ad-hoc scan of the just-written flat config.
  const { scanNow } = await prompts({
    type: 'confirm',
    name: 'scanNow',
    message: 'Run a scan now?',
    initial: true,
    stdout: process.stderr,
  });
  if (scanNow === true && flags.onScanNow !== undefined) {
    return flags.onScanNow();
  }

  return 0;
}
