version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
  # Disable for packages that only exist in private repo
  - package-ecosystem: "npm"
    directory: "/packages/reasoning"
    open-pull-requests-limit: 0
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

