/**
 * .dino.yml generator — the exact config text `dino init` produces (#2160; extracted #2191).
 * Kept FREE of the interactive UI (ink/prompts) so it can be imported by CI tooling and bundled
 * without pulling the whole onboarding view graph. INV-1: never writes secrets (valueEnv only).
 */

import {
  appendOAuth2YamlLines,
  buildOAuth2AuthAnswers,
  type InitOAuth2Answers,
} from './init-oauth2';

/** #2160/#2161: auth answers for generated .dino.yml (never a secret value). */
export type InitAuthAnswers =
  | { type: 'none' }
  | { type: 'header'; header: string; scheme?: string; valueEnv: string }
  | InitOAuth2Answers;

const SAFE_PLAIN = /^[A-Za-z0-9._:/@+-]+$/;
// YAML-reserved plain scalars that parse to a non-string type. SAFE_PLAIN matches these, so they
// must be force-quoted or a value like `--auth-value-env true` round-trips to a boolean, not the
// string "true" (#2198). Both patterns are anchored + non-backtracking (no nested quantifiers).
const YAML_RESERVED_WORD = /^(?:null|true|false|~|\.inf|\.nan)$/i;
const YAML_NUMERIC_LEADING = /^[-+]?\.?\d/; // anything YAML could read as a number → quote (safe over-approx)

/** Emits a YAML-safe single-line scalar that round-trips to the exact original string (INV-10). */
export function yamlScalar(value: string): string {
  const isPlainSafe =
    SAFE_PLAIN.test(value) && !YAML_RESERVED_WORD.test(value) && !YAML_NUMERIC_LEADING.test(value);
  return isPlainSafe ? value : JSON.stringify(value);
}

export function buildAuthAnswers(answers: {
  authType?: unknown;
  authHeader?: unknown;
  authScheme?: unknown;
  authValueEnv?: unknown;
  oauth2TokenEndpoint?: unknown;
  oauth2ClientIdEnv?: unknown;
  oauth2ClientSecretEnv?: unknown;
  oauth2Scope?: unknown;
}): InitAuthAnswers | undefined {
  if (answers.authType === 'oauth2') {
    return buildOAuth2AuthAnswers(answers);
  }
  if (answers.authType !== 'header') return { type: 'none' };
  const header =
    typeof answers.authHeader === 'string' && answers.authHeader.trim().length > 0
      ? answers.authHeader.trim()
      : 'Authorization';
  const valueEnv =
    typeof answers.authValueEnv === 'string' && answers.authValueEnv.trim().length > 0
      ? answers.authValueEnv.trim()
      : 'DINO_API_TOKEN';
  const schemeRaw = typeof answers.authScheme === 'string' ? answers.authScheme.trim() : '';
  if (schemeRaw.length > 0) {
    return { type: 'header', header, scheme: schemeRaw, valueEnv };
  }
  return { type: 'header', header, valueEnv };
}

/** Build YAML string from answers. INV-1: no secrets. */
export function buildConfigYaml(answers: {
  endpoint: string;
  protocol: string;
  auth?: InitAuthAnswers;
  specUrl?: string;
}): string {
  const lines: string[] = [
    // Branded canonical schema (mirrors packages/cli/schema.json); resolves for IDE validation.
    '# yaml-language-server: $schema=https://usedino.dev/schema.json',
    '# Generated by dino init: see https://usedino.dev/docs for all options',
    '',
    `endpoint: ${yamlScalar(answers.endpoint)}`,
    `protocol: ${yamlScalar(answers.protocol)}`,
  ];

  if (
    answers.protocol === 'rest' &&
    typeof answers.specUrl === 'string' &&
    answers.specUrl.length > 0
  ) {
    lines.push(`specUrl: ${yamlScalar(answers.specUrl)}`);
  }

  const auth = answers.auth;
  if (auth?.type === 'header') {
    lines.push('auth:', '  type: header', `  header: ${yamlScalar(auth.header)}`);
    if (auth.scheme && auth.scheme.length > 0) {
      lines.push(`  scheme: ${yamlScalar(auth.scheme)}`);
    }
    lines.push(`  valueEnv: ${yamlScalar(auth.valueEnv)}`);
  } else if (auth?.type === 'oauth2') {
    appendOAuth2YamlLines(lines, auth, yamlScalar);
  }

  lines.push('');
  return lines.join('\n');
}
