/**
 * .dino.yml generator — the exact config text `dino init` produces (#2160; extracted #2191).
 * Kept FREE of the interactive UI (ink/prompts) so it can be imported by CI tooling and bundled
 * without pulling the whole onboarding view graph. INV-1: never writes secrets (valueEnv only).
 */

import { appendOAuth2YamlLines, type InitOAuth2Answers } from './init-oauth2';

/** #2160/#2161: auth answers for generated .dino.yml (never a secret value). */
export type InitAuthAnswers =
  | { type: 'none' }
  | { type: 'header'; header: string; scheme?: string; valueEnv: string }
  | InitOAuth2Answers;

/** Build YAML string from answers. INV-1: no secrets. */
export function buildConfigYaml(answers: {
  endpoint: string;
  protocol: string;
  auth?: InitAuthAnswers;
  specUrl?: string;
}): string {
  const lines: string[] = [
    // Branded canonical schema (mirrors packages/cli/schema.json); resolves for IDE validation.
    '# yaml-language-server: $schema=https://usedino.dev/schema.json',
    '# Generated by dino init: see https://usedino.dev/docs for all options',
    '',
    `endpoint: ${answers.endpoint}`,
    `protocol: ${answers.protocol}`,
  ];

  if (
    answers.protocol === 'rest' &&
    typeof answers.specUrl === 'string' &&
    answers.specUrl.length > 0
  ) {
    lines.push(`specUrl: ${answers.specUrl}`);
  }

  // #2160/#2161: default format is markdown (flag-level); do not emit format in generated yaml.
  // Emit a real auth block (header or oauth2); never `enabled: true`.
  const auth = answers.auth;
  if (auth?.type === 'header') {
    lines.push('auth:', '  type: header', `  header: ${auth.header}`);
    if (auth.scheme && auth.scheme.length > 0) {
      lines.push(`  scheme: ${auth.scheme}`);
    }
    lines.push(`  valueEnv: ${auth.valueEnv}`);
  } else if (auth?.type === 'oauth2') {
    appendOAuth2YamlLines(lines, auth);
  }

  lines.push('');
  return lines.join('\n');
}
